// Generated by CoffeeScript 1.9.3
(function() {
  var angularHumanize;

  angularHumanize = angular.module("angularHumanize", []);

  angularHumanize.service("humanize", function() {
    return function(text, mode) {
      var i, len, ref, result, word;
      if (mode == null) {
        mode = "standard";
      }
      result = [];
      ref = text.split(" ");
      for (i = 0, len = ref.length; i < len; i++) {
        word = ref[i];
        if (word.length > 2 || mode === "strict") {
          word = word[0].toUpperCase() + word.slice(1);
        }
        result.push(word);
      }
      return result.join(" ");
    };
  });

  angularHumanize.filter("humanize", function(humanize) {
    return function(input, mode) {
      return humanize(input, mode);
    };
  });

}).call(this);
